### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by megacoder999** [pivovarit/articles#17]
Hello,
I got this message 
 java -jar kotlin-null-nonsafety-1.0.jar
no main manifest attribute, in kotlin-null-nonsafety-1.0.jar

May you add some extra description about how to test the code ?

**Comment by pivovarit** [comment]
Sure, will add instructions soon - in most cases I'm using simple unit-testing infrastructure to squeeze multiple examples in a single file. So, if you want to run those samples, just open them in your IDE and run

Also, it's great to see that someone is trying to actually use those snippets :)

**Comment by megacoder999** [comment]
👍
