### ISSUE TITLE
Still swap in lazy randomized java stream

### ISSUE THREAD

**Issue by leventov** [pivovarit/articles#23]
https://github.com/pivovarit/articles/blob/d9476fa820e941eb5d62aca0a6068ebc18e7bc4d/java-random-stream/src/main/java/com/pivovarit/stream/RandomSpliterator.java#L35-L40

It seems to me that you could still use swap with an element at index that is incremented with each tryAdvance() call. In the spirit of Fisher–Yates shuffle.

**Comment by pivovarit** [comment]
Good idea, we'll try it out and update the article, thanks!

**Comment by pivovarit** [comment]
Is that what you meant? I will run benchmarks soon, I'm really curious about the results since costly`System#arrayCopy` are gone now.

https://github.com/pivovarit/articles/pull/24

**Comment by pivovarit** [comment]
Turned out quite nice :) thanks!
![chart-5](https://user-images.githubusercontent.com/2182533/50650727-96665f00-0f81-11e9-9eb9-ca519727df5d.png)
