### ISSUE TITLE
AntipatternsTest Chaining map() and filterNotNull() example is wrong

### ISSUE THREAD

**Issue by ftorkler** [pivovarit/articles#75]
Hi, thx for your great article about the kotlin anitpatterns. I stumbled on a small error in section 3 about chaining map vs filterNoNull usage:

```
val list = listOf(1, 2, 3, null)

list
  .filterNotNull()
  .map { it.toString() }

list.mapNotNull { it.toString() }
```
It says those two expression have the same result, but they don't.
The second `mapNotNull` statement includes the `null` value.

The first result: `[1, 2, 3]`
The second result: `[1, 2, 3, null]`

Maybe you can fix this, as kotlin learners (like me) might stumble upon this as well.

**Comment by pivovarit** [comment]
That's weird - let me double-check and fix as soon as possible. 

Maybe the method semantics changed over time? 🤔

**Comment by pivovarit** [comment]
Ok, got it - it was a subtle typo. I missed the question mark:

```
list.mapNotNull { it?.toString() }
```

**Comment by pivovarit** [comment]
Corrected already, let me know if all is good and let me know if the issue is closeable

**Comment by ftorkler** [comment]
Yes, now it makes sense :) Thx for the quick fix!
